### DISCUSSION TITLE
Version 2.0: Post your ideas here

### DISCUSSION THREAD

**Discussion by tony** [tmux-python/tmuxp#760] [Ideas]
2.0 is where we can allow major changes (given proper notice)

The final 1.x versions will gradually introduce 2.0 features where possible - providing they don't break existing APIs - and will give deprecation warnings

- asyncio, including support for `sleep_before`/`sleep_after` #758
- Configuration
  - Syntax consistency
  - Allow passing empty configuration in more places
  - TOML
  - JSON w/ comments

**Comment by tony** [comment]
Configuration syntax ideas

```yaml
name: optional (infer by filename)
windows:
- name: window
  options:
    sleep_before: 1
  panes:
  - commands:
    - cmd: test 1
      options:
        sleep: 1
    - cmd: test 2
      options:
        sleep: 1
      tmux_options:
        pane_name: 'My second pane'
```

see also @rafi in #237
