### DISCUSSION TITLE
sequential ordering of command execution

### DISCUSSION THREAD

**Discussion by cnut1648** [tmux-python/tmuxp#802] [Q&A]
Hey, I mainly use ssh to login to a remote server. Sometimes I need to run a bunch of scripts, but some scripts depend on the output of some other scripts. Therefore it would be helpful if I could make some of my ssh window's commands start execution only after previous ones finish executation.
Currently I have something like this as a workaround
```
- window_name: script A
    window_shell: /bin/bash
    panes:
      - >
        time_consuming_script.sh
  - window_name: script B
    window_shell: /bin/bash
    panes:
      - >
        sleep estimate_time_for_script_A
        script_that_depends_on_script_A.sh
```
Of course this is far from perfect; some other more complicated methods include polling to check if the output of script A exists. But I just wonder if command execution control is possible for tmuxp. 
Thanks!
