### DISCUSSION TITLE
Environmental variable inheritance

### DISCUSSION THREAD

**Discussion by tony** [tmux-python/tmuxp#846] [Ideas]
A parent option, like `pass_environment`

```yaml
tmuxp_options:
  pass_environment: true
session_name: a session
```

Where `pass_environment` can be set at any object level, and all descendants inside have the variables passed. Then, they can be opted out by setting `pass_environment: false` at a lower level.

```yaml
tmuxp_options:
  pass_environment: true
environment:
  tippy: session variable
  toppy: session variable
windows:
  - panes:
      - shell_command:
        - echo "$TIPPY"
        - echo "$TOPPY"
      - tmuxp_options:
          pass_environment: false
        shell_command:
        - echo "$TIPPY"
        - echo "$TOPPY"
  - tmuxp_options:
      pass_environment: false
    panes:
      - shell_command:
        - echo "$TIPPY"
        - echo "$TOPPY"
```
