### DISCUSSION TITLE
Spawn a window without a name

### DISCUSSION THREAD

**Discussion by konomikitten** [tmux-python/tmuxp#938] [Q&A]
How do I spawn a window without a name?

I've tried:

```yml
session_name: default
windows:
  - windown_name:
    - pane:
      -
```

Which gives an str expected error.

```yml
session_name: default
windows:
  - windown_name: ''
    - pane:
      -
```

Which results in a blank window name.

I just want to do what I'd normally do in tmux with `new-window`.
