### ISSUE TITLE
Paths in windows' start_directory should be considered relative to the session's start_directory

### ISSUE THREAD

**Issue by stratoukos** [tmux-python/tmuxp#11]
If a relative path is specified in a window's start_directory, it should be considered relative to the session's. For example, in the following config:

``` yaml
session_name: test
start_directory: ~/projects/test
windows:
  - start_directory: dir/inside/project
  - panes:
    - pwd
```

the pane's pwd should be "~/projects/test/dir/inside/project". Right now it is "/".
