### ISSUE TITLE
main-pane default layouts not getting reasonable sizes

### ISSUE THREAD

**Issue by oblitum** [tmux-python/tmuxp#314]
For the following session:

```yaml
session_name: foo
windows:
- layout: main-vertical
  panes:
  - blank
  - blank
  - blank
```

The result is:

![screenshot](https://i.imgur.com/ZWLm5DC.png)

Where the main pane is the left one, it's smaller than the others non main panes.

- `tmuxp load -d ./foo.yaml`
- tmux 2.6/2.5
- tmuxp 1.3.5/1.3.2
- libtmux 0.7.7/0.7.1
