### ISSUE TITLE
Sessions with zoomed panes now start to lose its zoom state when refocused

### ISSUE THREAD

**Issue by oblitum** [tmux-python/tmuxp#316]
First time I see this behavior, must be due to the recent changes.

With at least two sessions open, chose one and have multiple panes open on it. Zoom one of the panes (prefix + z) and then switch to another session. Now switch back to the session with the zoomed pane. On switching back the zoom state is lost.

- `tmuxp load -d ./foo.yaml`
- tmux 2.6
- tmuxp 1.3.5
- libtmux 0.7.7

**Comment by oblitum** [comment]
I'm getting a tmux message when switching back: "no previous window".

**Comment by oblitum** [comment]
The session must be created by tmuxp, I'm using this one:

```yaml
session_name: foo
windows:
- layout: main-vertical
  options:
    main-pane-width: 160
  panes:
  - blank
  - blank
  - blank
```

I start it from inside a tmux session (`tmuxp load -y ./foo.yaml`, `-y` or `-d` doesn't matter). I've noticed that I do get this message "no previous window", right when I start and enter the session with `tmuxp load -y ./foo.yaml`.
