### ISSUE TITLE
focus: true doesn't work if shell_command: command is being used.

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#33]
``` yaml

session_name: logbook
start_directory: ~/study/python/logbook
windows:
- layout: 67d3,239x56,0,0[239x37,0,0,15,239x18,0,38{119x18,0,38,17,119x18,120,38,16}]
  focus: true  # focus works
  panes:
  - shell_command:
    - vim
    focus: true  # works!
  - pane
  - pane
  window_name: logbook
- layout: fbd5,239x56,0,0[239x33,0,0,18,239x22,0,34{119x22,0,34,20,119x22,120,34,19}]
  panes:
  - shell_command: vim
    focus: true  # focus Breaks!
  - pane
  - pane
  start_directory: docs
  window_name: docs
```
