### ISSUE TITLE
Focus doesn't work

### ISSUE THREAD

**Issue by vinipsmaker** [tmux-python/tmuxp#370]
I'm a new `tmuxp` user (have been using `tmux` for some months and decided to give a try to tmux session managers) and it doesn't focus on the proper window at all. I've tried several different combinations and none works. My last try was:

```
session_name: barao
windows:
- window_name: spare
  panes: []
- window_name: git
  focus: true
  start_directory: /home/vinipsmaker/Projetos/blinktrade/barao-gateway
  panes:
  - git status
- window_name: build
  start_directory: /home/vinipsmaker/Projetos/blinktrade/barao-gateway/build
  panes:
  - '#make -j5'
- window_name: services
  start_directory: /home/vinipsmaker/Projetos/blinktrade/barao-gateway/tools
  panes:
  - '#./dumb_authenticator.py'
- window_name: journald
  panes:
  - '#journalctl SYSLOG_IDENTIFIER=blinktrade-barao-gateway -o json-pretty -f'
```

Window `services` was end up being the window focused once I load the session. No idea why this happens.

My system:

- ArchLinux.
- tmux 2.6
- tmuxp 1.4.0
