### ISSUE TITLE
create pane failed: pane too small

### ISSUE THREAD

**Issue by ThiefMaster** [tmux-python/tmuxp#378]
Not sure if this can be fixed in tmuxp somehow or is a general tmux shortcoming...

But when trying to load a tmuxp config containing this window definition, it fails with "pane too small":

```yaml
  # 2 - indico
  - window_name: indico
    start_directory: ~/dev/indico/src
    focus: true
    layout: '7311,317x91,0,0[317x2,0,0,5,317x88,0,3{159x88,0,3[159x42,0,3,6,159x41,0,46,145,159x3,0,88,93],157x88,160,3[157x42,160,3,8,157x45,160,46,9]}]'
    panes:
      - tail -f ../data/log/indico.log
      - shell_command:
          - setopt ignoreeof
          - clear
      - focus: true
        shell_command:
          - setopt ignoreeof
          - clear
      - shell_command:
          - setopt ignoreeof
          - ./bin/maintenance/build-assets.py indico --dev --watch
      - start_directory: ~/dev/indico/plugins/public
        shell_command:
          - setopt ignoreeof
          - clear
      - start_directory: ~/dev/indico/plugins/cern
        shell_command:
          - setopt ignoreeof
          - clear
```
