### ISSUE TITLE
Empty line in `shell_command_before` results in Exception

### ISSUE THREAD

**Issue by MaPePeR** [tmux-python/tmuxp#391]
```yaml
session_name: abc
windows:
- window_name: name
  layout: tiled
  shell_comamnd_before:
    - A=132
    - #B=456
    - C=789
  panes:
    - echo 1
    - echo 2
    - #echo 3
    - echo 4
```
