### ISSUE TITLE
start_directory doesn't work when set on session, window and pane

### ISSUE THREAD

**Issue by rightaway** [tmux-python/tmuxp#422]
When `start_directory` is set on all of session, window, and pane, it doesn't work as expected.

It should concatenate directories for session + window + pane, inheriting from the parent level if nothing is specified.

So a pane that has no start_directory on window should get the directory from session + pane. And a pane that has nothing set for itself should get the directory from session + window.

**Comment by rightaway** [comment]
Is it working for anyone else? If not would the maintainers be interested in including such a feature at some point?

**Comment by rightaway** [comment]
@tony Thanks for taking care of https://github.com/tmux-python/tmuxp/issues/326. Do you think you could take a look at this issue too? It's the only thing holding me back from getting rid of tmuxinator once and for all and finally switching to tmuxp! :)

**Comment by rightaway** [comment]
@tony Thanks for taking care of #326. Do you think you could take a look at this issue too? It's the only thing holding me back from getting rid of tmuxinator once and for all and finally switching to tmuxp! :)

**Comment by tony** [comment]
@rightaway I pinned this

Is there a PR for it? Do you have any more info that'd be helpful getting this added in tmuxp?

**Comment by rightaway** [comment]
I don't have a PR myself but I'll provide any additional info that you need.

```yml
start_directory: /top/level
windows:
  - panes:
      - command_one
  - start_directory: two
    panes:
      - command_two
      - start_directory: three/four
        shell_command: command_three
      - start_directory: ~/my/four
        shell_command: command_four
  - start_directory: ~/my/five
    panes:
      - start_directory: under_five
        shell_command: command_five
```

So command_one should be in /top/level, command_two should be in /top/level/two, and command_three should be in /top/level/two/three/four. This is because these are relative paths so they get appended.

But because command_four has an absolute path, it should be in ~/my/four. Same with command_five, which should be in ~/my/five/under_five.
