### ISSUE TITLE
Environment variables fail when not strings

### ISSUE THREAD

**Issue by Cybolic** [tmux-python/tmuxp#503]
When giving a numerical environment variable in a config, such as `SERVER_PORT: 1999`, tmuxp will break with a `TypeError` exception but provide no more information as to why.

The issue is in `config.py` line 216:
```
val = expandshell(val)
```

I believe this line should either be wrapped in a `try` and provide an error message telling which variable didn't work or just cast all environment variables to strings (as in `val = expandshell(str(val))`). Whether it should refuse to continue or just ignore the error I'll leave up to the maintainer.

Example config that fails:
```
session_name: Example
environment:
  SERVER_PORT: 1999
windows:
  - window_name: something
    panes:
      - shell_command: echo "server port: ${SERVER_PORT}"
```
