### ISSUE TITLE
tmux percentage pane sizing

### ISSUE THREAD

**Issue by deliciouslytyped** [tmux-python/tmuxp#525]
I was peeking through the tmux 3.0 changelogs and this entry caught my eye:
```
* Add support for percentage sizes for resize-pane ("-x 10%"). Also change
  split-window and join-pane -l to accept similar percentages and no longer
  document -p.
```
If that is what I think it is, it would be interesting to have support for such relative sizes in tmuxp.

**Comment by denisw** [comment]
It seems as if percentage sizes work just fine with the existing tmuxp size options. I just tried the following successfully:

```yaml
session_name: percentage-pane-size
windows:
  - window_name: example
    layout: main-vertical
    options:
      main-pane-width: '60%'
    panes:
      -
      -
```

That being said, it would be great if such a percentage were used by default for `main-pane-width` / `main-pane-height`, to avoid the situation on large screens were the "main" pane is actually much smaller than the other ones (see #314).
