### ISSUE TITLE
Plugin system

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#530]
Access [`Session`](https://libtmux.git-pull.com/en/latest/sessions.html), [`Window`](https://libtmux.git-pull.com/en/latest/windows.html) or [`Pane`](https://libtmux.git-pull.com/en/latest/panes.html) object being adjusted.

This would allow hook-like access to tmux session, window, and panes throughout the workspace builder lifecycle.

```yaml
plugins:
  - 'my_tmuxp_plugin.plugin.TmuxResurrect'
session_name: my session
windows:
- window_name: my window
  layout: tiled
  shell_command_before:
    - cd ~/                    # run as a first command in all panes
  panes:
    - echo pane
    - echo pane
```

Assume a git repo `my_tmuxp_plugin` with a directory `my_tmuxp_plugin` inside it, and a pypi package called `my_tmuxp_plugin`:

`my_tmuxp_plugin/plugin.py`:

```python
class TmuxResurrect:
    def before_workspace_builder(self, session):
        # On blank workspace, after session created, but before any windows/panes/commands entered

        # technically, it'd be possible to do any kind of subprocess call here as well

    def before_script(self, session):
        # access to libtmux session object in tmuxp load

   def reattach(self, session):
       # if session_name already live, before reattaching

   def on_window_create(self, window):
        if window.window_name == 'my window':
            # do stuff

   def after_window_finished(self, window):  # after commands stuff commands finally entered
       pass
```
