### ISSUE TITLE
Multiple configs in single file

### ISSUE THREAD

**Issue by rightaway** [tmux-python/tmuxp#573]
I'd like to have multiple configs in a single file, rather than having to spread them across multiple files. If a yaml file contains an array of objects, then tmuxp should load whichever of them matches, like `tmuxp load first` or `tmuxp load second`.

```yaml
- session_name: first
  windows: ...
- session_name: second
  windows: ...
```

The config file can then be a single file under `~/.tmuxp/config.yml`.
