### ISSUE TITLE
My configuration doesn't attach to a docker container

### ISSUE THREAD

**Issue by lifeBalance** [tmux-python/tmuxp#575]
Running macOS, trying to create a quite simple session; in one panel I connect to a Docker container. Why tmuxp doesn't allow me to start session in a Docker container?
```
session_name: Exercism_Bash
start_directory: ./
windows:
  - window_name: Linux
    layout: even-horizontal
    panes:
    - shell-command-before:
      - cd "~/Public/exercism/bash"
      - vim .
    - shell-command-before:
      - docker container exec -it ubuntu-cont bash
      - cd "~/macOS/exercism/bash"
      - clear
  - window_name: macOS
    layout: even-horizontal
    panes:
      - cd "~/Public/exercism/bash"
      - cd "~"
```
I tried the same with Tmuxinator and works flawlessly.
