### ISSUE TITLE
How can I set the session_name dynamically based on the current directory?

### ISSUE THREAD

**Issue by sluther-electro** [tmux-python/tmuxp#634]
I've created a shared tmux config in ~/.tmuxp/org.yml. I'd like to set the session_name dynamically based on the directory I'm launching tmux from using a shared config file.

I.e. if my path is `/Users/sluther/Projects/org/project_1` and I use `tmuxp load org` to start tmux, I want the `session_name` to be set to `project_1`. I've tried the following:

Here's my `before-org.sh` script
```bash
#!/bin/sh
export TMUX_SESSION_NAME=${PWD##*/}
```

And here's my `org.yml` file:
```YAML
session_name: "$TMUX_SESSION_NAME"
start_directory: "$PWD"
before_script: ~/.tmuxp/org-before.sh
```

Is there any way to make this work?
