### ISSUE TITLE
Support more than 1 sessions

### ISSUE THREAD

**Issue by nicolas-g** [tmux-python/tmuxp#644]
### Feature Request: Support the creation of more than 1 sessions.

Right now in a single **tmuxp** yaml config file, only 1 session seems to be supported. If you define more than one, only the last session will be effective.

Will be nice if we can define more than 1 session in a single file like this:
```
session_name: Session1
windows:
  - window_name: S1Window1
  - window_name: S1Window2

session_name: Session2
windows:
  - window_name: S2Window1
  - window_name: S2Window2
```
