### ISSUE TITLE
config: Allow passing environment into environment variables

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#670]
related: #669

assuming 

```yaml
session_name: django
environment:
  SERVER_PORT: "8012"
- window_name: test ${SERVER_PORT}
  layout: main-horizontal
  focus: true
  panes:
  - focus: True
  - blank
```
Allow `window_name` to receive `SERVER_PORT` without having to do `env SERVER_PORT=8012 tmuxp load ./file.yaml`

### Step 1: Provide a summary of your problem
  * For general technical questions, problems or feature requests related to the code **in this repository** file an issue.

### Step 2: Provide tmuxp details
  * Include output of `tmuxp debug-info`
  * Include any other pertinant system info not captured

#### Steps to reproduce:
  1. _____
  2. _____
  3. _____

#### Observed Results:
  * What happened?  This could be a description, log output, etc.

#### Expected Results:
  * What did you expect to happen?

#### Relevant Code:
  ```
  // TODO(you): paste here tmuxp configuration (YAML / JSON) you are having issues with.
