### ISSUE TITLE
Possible to send tmux commands to panes, e.g. to set the pane title?

### ISSUE THREAD

**Issue by ionsquare** [tmux-python/tmuxp#739]
### Step 1: Provide a summary of your problem
I'd like to know how to set pane names in a tmuxp yaml layout file

### Step 2: Provide tmuxp details
N/A

### Step 3: Describe the problem:
The following tmux commands will set pane names and show them at the top of each pane, like a title bar:
```bash
tmux set -g pane-border-status top
tmux select-pane -T 'My Pane Title'
```

If I set these commands as regular shell commands under different panes in the tmuxp layout yaml, I either get an tmux error message saying `No previous window`, or if I add in a sleep before they run, only the last focused pane will have the title set.

#### Observed Results:
Titles are not applied to the correct panes when tmux commands are entered as `shell_command` entries.

#### Expected Results:
I'm hoping these is a way to directly apply raw tmux commands to specific panes in the layout file, without having to go through the tmux command as a `shell_command`.

Is there a way to specify raw tmux commands to send to a pane?

#### Relevant Code:
 ```yaml
session_name: example

windows:
  - window_name: example
    panes:
      - shell_command:
        - tmux select-pane -T 'primary'
      - shell_command:
        - tmux select-pane -T 'secondary'
```

**Comment by tony** [comment]
Would a plugin do the trick? https://tmuxp.git-pull.com/plugin_system.html

This gives access to libtmux

**Comment by tony** [comment]
Somewhat random: I'm debating creating a new feature:

`tmuxp run-script <file>`

This would let the user boot into `libtmux` directly and just have a custom script to set up tmux.

This would make it easy for a case like yours to get the results you want via python

**Comment by tony** [comment]
Back to your config:

This is the first time I've seen setting the pane title. Any more details on the use case?

**Comment by ionsquare** [comment]
I'm not too familiar with plugins yet, I just had a look at the link you shared and it looks pretty neat, but I don't immediately see a way I could go about specifying pane titles in the layout file. I'll try to find some time to play around with that though.

Use case: I have a lot of stuff running and tailing logs, and I lose track of which pane is running what. Here's a simplified example:
```yaml
session_name: work

windows:
  - window_name: logs
    panes:
    - docker compose -f service-1.yml up
    - docker compose -f service-2.yml up
    - docker compose -f service-3.yml up
    - npm run build -- --watch --mode=development
    - gulp
    - bazel run //primary-app/server
    - bazel run //dependency/server
    - tail -F /var/log/nginx/error.log
    - tail -F /var/log/php_errors.log
  - window_name: curl
    panes:
    - curl -v -b cookie.jar -c cookie.jar "http://localhost/some/endpoint 2>>/tmp/curl.log
    - watch -n 1 cat cookie.jar
    - tail -f /tmp/curl.log
  - window_name: remote ssh
    panes:
    - ssh host1
    - ssh host2
    - ssh host3
    - blank
  - window_name: remote logs
    panes:
    - ssh host1 tail -f /var/log/something.log
    - ssh host2 tail -f /var/log/something.log
    - ssh host3 tail -f /var/log/something.log
```

The example is a bit exaggerated to illustrate the problem a bit better, in real life the panes are spread over different tmux sessions and a few more windows, but it's still enough stuff running in each window that it's easy to lose track of which log file I'm looking at in a particular pane. Having the pane titles for some windows helps me spend less time trying to remember what I'm looking at.

It's really useful to have the logs all in the same window so when I'm troubleshooting a problem I can instantly see which service is causing the problem. Pane titles can be really useful for keeping track of things, saving time.

**Comment by piotr-dobrogost** [comment]
Duplicate of issue #384 (Add support for tmux 2.3's pane status text)?

**Comment by ionsquare** [comment]
I came up with a workaround by entering the commands in the last pane and specifying the pane numbers. Example:

```yaml
  - window_name: curl
    panes:
    - curl -v -b cookie.jar -c cookie.jar "http://localhost/some/endpoint 2>>/tmp/curl.log
    - watch -n 1 cat cookie.jar
    - shell_command:
      - tmux set -w pane-border-status top
      - tmux select-pane -T curl -t 0
      - tmux select-pane -T watch -t 1
      - tmux select-pane -T tail -t 2
      - tail -f /tmp/curl.log
```
