### ISSUE TITLE
Feature request:  `if:` to optionally open windows / panes

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#741]
`if:` could potentially execute python or shell and interpolate environmental variables

```yaml

windows:
- window_name: window
  if: import os; os.path.isdir(~/work/myproject)

```
