### ISSUE TITLE
`sleep` / `wait` for commands

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#748]
https://github.com/tmux-python/tmuxp/issues/704#issuecomment-905747160

```yaml
session_name: 'glorp'
# Reference this issue for why we need to use `source` here:
# https://github.com/tmux-python/tmuxp/issues/412
shell_command_before:
- cmd: source $(poetry env info --path)/bin/activate
  sleep_before: 1
  sleep_after: 1
windows:
  - panes:
    - echo "hello"
```

You'd this this would be possible

```yaml
session_name: 'glorp'
# Reference this issue for why we need to use `source` here:
# https://github.com/tmux-python/tmuxp/issues/412
windows:
  - panes:
    - shell_command:
      - cmd: source $(poetry env info --path)/bin/activate
        sleep_after: 1
      - echo "hello"
```
