### ISSUE TITLE
Per-command options

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#751]
Fixes #53 #750 

Options like `sleep: 3` and `enter: false` should be allowed to be passed at the per-command level.

Internally, individual tmuxp commands are only strings. 

Now:

```yaml
windows:
  panes:
  - shell_command:
    - echo "hello"
```

What the syntax needs:

```yaml
windows:
  panes:
  - shell_command:
    - cmd: echo "hello"
      enter: false
      sleep: 2
```

~~~~

Earlier conversations: https://github.com/tmux-python/tmuxp/issues/53#issuecomment-1066092004
