### ISSUE TITLE
Eval python code

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#771]
_In addition to our plugin system #530 #628_

We can allow inserting of scripts into "commands"

### `pane.eval`

```yaml
windows:
  panes:
  - shell_command:
    - eval: >
      def run(pane):
          # total access up the tree
          window = pane.window
          session = pane.window.session
          server = pane.window.server.server

          pane.send_keys(f'echo "ran this by hand in {window.window_name} of {session.session_name} in {server}', enter=True)
    - cmd: echo "hello"
```

### `pane.eval_script`

See also `tmuxp run-script` #772

script.sh:

```python
def run(pane):
    # total access up the tree
    window = pane.window
    session = pane.window.session
    server = pane.window.server.server

    pane.send_keys(f'echo "ran this by hand in {window.window_name} of {session.session_name} in {server}', enter=True)
```

```yaml
windows:
  panes:
  - shell_command:
    - eval_script: script.py
    - cmd: echo "hello"
```
