### ISSUE TITLE
WorkspaceBuilder: allow passing tmux session args

### ISSUE THREAD

**Issue by tony** [tmux-python/tmuxp#810]
Allow params to `new-session` should be passable via `session_options`

```yaml
session_name: session
session_options:
  # ...
```

From tmux manpages:

```console
$ tmux new-session -d 'vi ~/.tmux.conf' \; split-window -d \; attach
```

```console
tmux new-sesssion vi
```
