### ISSUE TITLE
Problem with colon (:) in pane commands in yaml-session-files

### ISSUE THREAD

**Issue by abelbabel** [tmux-python/tmuxp#820]
Hi,

there seems to be a problem with colons in pane commands. See the following example yaml-session-file. Escaping with backslash (\\) has no effect. Using single ticks (') instead of double ticks (") has no effect.
I'm using tmuxp 1.9.3 on Ubuntu 18.04, installed via pip.

```
session_name: buggy_session
windows:
  - window_name: bug_window
    panes:
      # the following works
      - echo "a bug with colon:"
      # the following gives no output
      - echo "a bug with colon: a"
      # the following results in no start of session and in error: yaml.scanner.ScannerError: while scanning a quoted scalar
      #- echo "a bug with colon: "
```

Maybe I missed a documentation somewhere, which says how to deal with colons in commands. Otherwise (if I did not and if it is not really a bug) a documentation would be great.

Kind regards,
abelbabel
