### ISSUE TITLE
`shell_command_before:` under the `panes:` issue.

### ISSUE THREAD

**Issue by 0xhunster** [tmux-python/tmuxp#827]
I want to add `shell_command_before:` under the `panes:`. How is it possible?

```
session_name: 4-pane-split
windows:
  - window_name: dev window
    layout: tiled

    panes:
      - shell_command: # pane no. 1
        shell_command_before:
        - ssh test@192.168.31.229

    panes:
      - shell_command:
        shell_command_before:
        - ssh test@192.168.31.229
```
