### ISSUE TITLE
Issue with using `-t` in pane commands in session files

### ISSUE THREAD

**Issue by GBlackburnMicrosoft** [tmux-python/tmuxp#915]
This issue is observed with both tmuxp 1.40.0 and 1.39.0, it was _not_ present in 1.9.4.

### Summary

When a pane command includes the string `-t` it will not enter that command into the pane and will instead print it to screen in the shell where you ran the `tmuxp` command.

### Reproduction

Example configuration file:

```yaml
session_name: "Some-Session"
windows:
  - window_name: "Some-Window"
    layout: tiled
    panes:
      - shell_command:
        - echo "t - This echo's correctly."
      - shell_command:
        - echo "-a - This also echo's correctly."
      - shell_command:
        - echo "-t - This is never sent to the pane and instead printed to the current shell."
```

**Expected:**
Load this template using `tmuxp load` and you'll get three panes, all three panes have echoed out the expected message.

**Current outcome:**
When loading this template only the first two panes will have echoed out the expected message and the final one with `-t` in it then it prints out to the current shell.
