### ISSUE TITLE
How to escape the dollar sign?

### ISSUE THREAD

**Issue by yuis-ice** [tmux-python/tmuxp#945]
Here's an example tmuxp yaml config part: 

```
    panes:
      - shell_command:
        - autossh -t -p 30360 tmp@localhost 'PATH=~/.nvm/versions/node/v20.16.0/bin:\$PATH && cd pg && npx local-web-server -p 30361'
```

The problem is simply, the `$PATH` part expands on the tmux session (what I do not desire and expect), so I need to disable the feature (?) or safely escape such character(s).

**Comment by joseph-flinn** [comment]
It seems like the expansion of all environment variables comes from this line: 

https://github.com/tmux-python/tmuxp/blob/ef6b32a69632cf947e5c630e3b5d7ea26a4034b1/src/tmuxp/workspace/loader.py#L26

It doesn't look like there is currently a way to escape the dollar sign. I'll have to look further into the different cases where environment variables should and should not be expanded before proposing a solution.

<details>
  <summary>Debugging notes to future self</summary>

  - Manually running `:send-keys "echo '$PATH'" Enter` in tmux expands `$PATH`
  - Manually running `:send-keys 'echo "$PATH"' Enter` in tmux does _not_ expand `$PATH`
  - `pane.send_keys("PATH=$PATH")` works as expected (does not expand in pane)
    - Can quickly be tested `tmuxp shell`
    - Implies that `libtmux.pane.cmd()` works as expected
    - Implies that `libtmux.server.cmd()` works as expected
  - The issue has to be with how the command is loaded from the config 
  - Found it: `tmuxp.workspace.loader.expandshell()` defaults to expanding all `$` and `${}` with the user's local environment
 </details

**Comment by posita** [comment]
Question: Why is tmuxp expanding shell variables at all inside `shell_command`? What is the use case? [This](https://tmuxp.git-pull.com/configuration/examples/#environment-variables) is the only example I can find in the docs where expansion prior to shell evaluation is "required", but it's still a bit contrived and totally bricks reasonable expectations. Consider, e.g.:

```yaml
    - shell_command:
        - cmd: '( cd ~/dev/sandbox ; codex resume -C "${PWD}" )'
        - enter: false
```

Expected (and reinforced by nearly every other execution context):

```
$ ( cd ~/dev/sandbox ; codex resume -C "${PWD}" )
```

Actual:

```
$ ( cd ~/dev/sandbox ; codex resume -C /home/ubuntu )
```

Even in contexts that provide their own shell expansions (e.g., `Makefile`s, `crontab`s, etc.), escaping mechanisms are provided to make sure interpretation/expansion can deferred to the shell.

Another solution might be to refuse to expand inside `shell_command` at all, but provide an `export` directive for config-defined variables:

```yaml
environment:
  SERVER_PORT: "8009"
  LOCAL_ONLY_VAR: "not exported"
export: [SERVER_PORT]  # list of variables to set in the environment for sub-commands
windows:
  - panes:
    - shell_command:
        - cmd: 'echo "${SERVER_PORT} should be evaluated by the shell to which it has been exported' 
        - enter: false
```

An escaping mechanism is probably more ergonomic and comports with prior art.
