### ISSUE TITLE
Strange leading whitespace before shell command

### ISSUE THREAD

**Issue by raine** [tmux-python/tmuxp#975]
```
session_name: helloworld
windows:
  - window_name: dev
    start_directory: /home/parallels
    panes:
      - shell_command: "echo foo"
      - shell_command: "echo bar"
```

![Image](https://github.com/user-attachments/assets/ffdf8ecc-6422-4595-830b-709a76eb2cc0)

If you press up to get the previous command, there is leading whitespace in the command, so it's not just a rendering issue.

tmuxp 1.55.0, libtmux 0.46.0

**Comment by raine** [comment]
It appears to be a side effect of history suppression. If I do `suppress_history: false` I don't see the issue.

```
session_name: helloworld
windows:
  - window_name: dev
    suppress_history: false
    start_directory: /home/parallels
    panes:
      - shell_command: "echo foo"
      - shell_command: "echo bar"
```
