### ISSUE TITLE
Tmuxp is failing when loading a session

### ISSUE THREAD

**Issue by adaviloper** [tmux-python/tmuxp#977]
I'm not sure what the issue is here, but I started getting this issue recently:

## Stack trace
```
$ tmuxp load dots
[Loading] /Users/hackeysack09/.config/tmuxp/dots.yaml
Traceback (most recent call last):
  File "/opt/homebrew/bin/tmuxp", line 8, in <module>
    sys.exit(cli.cli())
             ~~~~~~~^^
  File "/opt/homebrew/Cellar/tmuxp/1.55.0/libexec/lib/python3.13/site-packages/tmuxp/cli/__init__.py", line 149, in cli
    command_load(
    ~~~~~~~~~~~~^
        args=CLILoadNamespace(**vars(args)),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        parser=parser,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Cellar/tmuxp/1.55.0/libexec/lib/python3.13/site-packages/tmuxp/cli/load.py", line 581, in command_load
    load_workspace(
    ~~~~~~~~~~~~~~^
        workspace_file,
        ^^^^^^^^^^^^^^^
    ...<2 lines>...
        **tmux_options,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/opt/homebrew/Cellar/tmuxp/1.55.0/libexec/lib/python3.13/site-packages/tmuxp/cli/load.py", line 391, in load_workspace
    _load_attached(builder, detached)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/tmuxp/1.55.0/libexec/lib/python3.13/site-packages/tmuxp/cli/load.py", line 139, in _load_attached
    builder.build()
    ~~~~~~~~~~~~~^^
  File "/opt/homebrew/Cellar/tmuxp/1.55.0/libexec/lib/python3.13/site-packages/tmuxp/workspace/builder.py", line 263, in build
    session = self.server.new_session(
        session_name=self.session_config["session_name"],
        **new_session_kwargs,
    )
  File "/opt/homebrew/Cellar/tmuxp/1.55.0/libexec/lib/python3.13/site-packages/libtmux/server.py", line 571, in new_session
    raise exc.LibTmuxException(proc.stderr)
libtmux.exc.LibTmuxException: ['server exited unexpectedly']
```

## dots.yaml
```yaml
session_name: Dotfiles
start_directory: ~/.dotfiles
windows:
  - window_name: .dotfiles
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Neovim Plugins
    start_directory: "~/.local/share/nvim/lazy"
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Tmux Plugins
    start_directory: "~/.config/tmux/plugins/tmux-theme"
    panes:
      - shell_command:
          - cmd: "c"
  - window_name: Tmux Fork
    start_directory: "~/Code/catppuccin-tmux/"
    panes:
      - shell_command:
          - cmd: "c"
```

## Versions
OS: MacOS 15.3.2
Brew: 4.4.31
Tmux: 3.5a
Tmuxp: 1.55.0
libtmux: 0.46.0

Not sure what else is necessary to provide.
